data_plumber_model:
  outputs:
    dev:
      type: duckdb
      path: "md:data_plumber_dev?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 1
    
    prod:
      type: duckdb
      path: "md:data_plumber_prod?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 4
  
  target: dev